[package]
name = "rust-rag-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
mongodb = "3.2.5"
serde = { version = "1.0.219", features = ["derive"] }
twox-hash = "2.1.1"
uuid = { version = "1.18.0", features = ["v4"] }
